# Generated by Django 4.2.16 on 2025-01-26 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channelscheduledmessage',
            name='scheduled_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 8, 8, 26, 756579)),
        ),
    ]
