# Generated by Django 4.2.16 on 2025-01-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_alter_channel_name_alter_channelmessage_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelscheduledmessage',
            name='scheduled_time',
            field=models.DateTimeField(),
        ),
    ]
