# Generated by Django 4.2.16 on 2025-01-25 07:33

import channel.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='channel',
            name='type',
            field=models.CharField(choices=[('public', 'PUBLIC'), ('private', 'PRIVATE')], default=channel.enums.ChannelType['PUBLIC'], max_length=30),
        ),
    ]
