# Generated by Django 4.2.16 on 2025-01-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_alter_channel_description_alter_channel_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelmessage',
            old_name='user',
            new_name='sender',
        ),
        migrations.AlterField(
            model_name='channel',
            name='type',
            field=models.CharField(choices=[('public', 'PUBLIC'), ('private', 'PRIVATE')], default='public', max_length=30),
        ),
        migrations.AlterField(
            model_name='channelmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('member', 'MEMBER')], default='member', max_length=6),
        ),
    ]
