# Generated by Django 4.2.16 on 2025-01-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_alter_channelmembership_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='type',
            new_name='channel_type',
        ),
    ]
