# Generated by Django 4.2.16 on 2025-01-28 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_rename_type_channel_channel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmessage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='channel.channel'),
        ),
    ]
