# Generated by Django 4.2.16 on 2025-01-25 19:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0004_rename_user_channelmessage_sender_alter_channel_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('name', 'owner')},
        ),
    ]
