# Generated by Django 4.2.16 on 2025-01-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_alter_channel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
