# Generated by Django 4.2.16 on 2025-02-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_alter_channelmessage_channel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelscheduledmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='channelscheduledmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='channel/messages/files/'),
        ),
        migrations.AlterField(
            model_name='channelscheduledmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='channel/messages/images/'),
        ),
        migrations.AlterField(
            model_name='channelscheduledmessage',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='channelscheduledmessage',
            table='channel_scheduled_message',
        ),
    ]
