# Generated by Django 4.2.16 on 2025-01-25 19:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0005_alter_channel_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelmembership',
            options={'ordering': ['-created_at'], 'verbose_name': 'ChannelMembership', 'verbose_name_plural': 'ChannelMemberships'},
        ),
        migrations.AlterUniqueTogether(
            name='channelmembership',
            unique_together={('channel', 'user')},
        ),
        migrations.AlterModelTable(
            name='channelmembership',
            table='channelMembership',
        ),
    ]
