# Generated by Django 4.2.16 on 2025-01-05 23:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notifications_enabled', models.BooleanField(default=False)),
                ('device_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
