# Generated by Django 4.2.16 on 2025-02-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_notificationpreference_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
