# Generated by Django 4.2.16 on 2025-02-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupscheduledmessage',
            options={'ordering': ['-created_at']},
        ),
    ]
