# Generated by Django 4.2.16 on 2025-01-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_grouppermission_can_send_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppermission',
            name='can_send_media',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='can_send_messages',
            field=models.BooleanField(default=True),
        ),
    ]
