# Generated by Django 4.2.16 on 2025-01-20 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0006_alter_group_owner_alter_groupmessage_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='sender',
            field=models.ForeignKey(on_delete=models.SET('delete_user'), related_name='send_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
