# Generated by Django 4.2.16 on 2025-01-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_alter_grouppermission_can_send_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppermission',
            name='can_send_messages',
            field=models.BooleanField(default=True),
        ),
    ]
