# Generated by Django 4.2.16 on 2025-01-22 21:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_alter_grouppermission_can_send_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
