# Generated by Django 4.2.16 on 2025-02-03 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledmessage',
            options={'verbose_name': 'Schedule Message', 'verbose_name_plural': 'Schedule Messages'},
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='scheduledmessage',
            table='schedule_message',
        ),
    ]
