# Generated by Django 4.2.16 on 2025-01-25 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmessage',
            name='scheduled_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 26, 23, 6, 18, 78989)),
        ),
    ]
