# Generated by Django 4.2.16 on 2025-01-26 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_scheduledmessage_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmessage',
            name='scheduled_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 8, 8, 26, 756579)),
        ),
    ]
