# Generated by Django 4.2.16 on 2025-01-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_scheduledmessage_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmessage',
            name='scheduled_time',
            field=models.DateTimeField(),
        ),
    ]
